# Generated by Django 3.2.19 on 2023-06-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
