# Generated by Django 3.2.19 on 2023-06-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0003_rename_updated_on_date_post_last_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_updated_on',
        ),
        migrations.AddField(
            model_name='post',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
